name: Android CI

on:
  workflow_dispatch:
    inputs:
        deploy_env:
          description: 'Deploy Env'
          required: true
          default: 'QA'
          type: choice
          options:
            - QA
            - PRODUCT
            
env:
  DEFAULT_ENVIRONMENT: ${{ vars.DEFAULT_ENVIRONMENT }}

jobs:
  ci:
    uses: liberty-app-sam-sang/my-actions/.github/workflows/blank.yml@main
    secrets: inherit
    with:
      java-version: 17
      deploy-env: ${{ inputs.deploy_env }}
